%YAML:1.0
vectorSize: 16
points_pos_x_0: 0
points_pos_y_0: 0
points_ver_x_0: 60
points_ver_y_0: 45
points_pos_x_1: 15602
points_pos_y_1: -248
points_ver_x_1: 1440
points_ver_y_1: 45
points_pos_x_2: 17641
points_pos_y_2: -298
points_ver_x_2: 1860
points_ver_y_2: 45
points_pos_x_3: 0
points_pos_y_3: 0
points_ver_x_3: 240
points_ver_y_3: 315
points_pos_x_4: 16974
points_pos_y_4: 846
points_ver_x_4: 1680
points_ver_y_4: 315
points_pos_x_5: 11704
points_pos_y_5: 1611
points_ver_x_5: 720
points_ver_y_5: 495
points_pos_x_6: 14308
points_pos_y_6: 2362
points_ver_x_6: 1200
points_ver_y_6: 585
points_pos_x_7: 15166
points_pos_y_7: 3178
points_ver_x_7: 1320
points_ver_y_7: 765
points_pos_x_8: 11349
points_pos_y_8: 3448
points_ver_x_8: 720
points_ver_y_8: 855
points_pos_x_9: 12874
points_pos_y_9: 3591
points_ver_x_9: 960
points_ver_y_9: 855
points_pos_x_10: 17500
points_pos_y_10: 3357
points_ver_x_10: 1680
points_ver_y_10: 855
points_pos_x_11: 10431
points_pos_y_11: 3690
points_ver_x_11: 600
points_ver_y_11: 945
points_pos_x_12: 18723
points_pos_y_12: 3497
points_ver_x_12: 1860
points_ver_y_12: 945
points_pos_x_13: 11151
points_pos_y_13: 4249
points_ver_x_13: 720
points_ver_y_13: 1035
points_pos_x_14: 17141
points_pos_y_14: 4366
points_ver_x_14: 1560
points_ver_y_14: 1035
points_pos_x_15: 17895
points_pos_y_15: 4165
points_ver_x_15: 1680
points_ver_y_15: 1035
